### PR TITLE
Makefile: config.mk: changes

### PR DESCRIPTION
**Pull request by sewnie**
something i had noticed is the usage of `$(NAME)`, what is the point of that? `stw` is shorter than it so i had removed it.

i also added `LDFLAGS` and `CPPFLAGS` and a copyright message to the new edited files.

please know i do not know makefiles and i am simply copying suckless's homework.

### CODE REVIEW

**Comment by sewnie** [comment]
i also hope you add a way for `stw` to have a version specified by the 2nd line of `config.mk`.

i also mainly added this if you saw [my comment](https://github.com/sineemore/stw/issues/13#issuecomment-1174980110), it changes `config.mk` not Makefile. and this is why i mainly created this PR.

**Comment by sewnie** [comment]
alternatively, we can try `pkg-config --cflags freetype2` and `pkg-config --libs freetype2` in Makefile instead of whats already there. what do you think?

**Comment by sineemore** [comment]
> alternatively, we can try `pkg-config --cflags freetype2` and `pkg-config --libs freetype2` in Makefile instead of whats already there. what do you think?

Probably, check st template file in void-packages. It uses pkg-config in config.mk file and is seems to work quite well.

https://github.com/void-linux/void-packages/blob/master/srcpkgs/st/template
https://git.suckless.org/st/file/config.mk.html

**Comment by sewnie** [comment]
both `fontconfig` and `freetype2` are used in st.

here its a frankenstein of `fontconfig` in `LIBS` and `freetype2` in `INCS`. i will add both for safety(?)

edit: now using only `fontconfig` as it also provides the same as if i requested for `freetype2`

**Pull request merged**
